chutney:
  db-server:
    base-dir: ./.chutney/data

spring:
  jpa:
    open-in-view: false
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: com.chutneytesting.SQLiteDialect
      hibernate.id.new_generator_mappings: false
  datasource:
    url: jdbc:sqlite:${chutney.db-server.base-dir}/sqlitesample.db
    username:
    password:
    configuration:
      maximum-pool-size: 5
