
chutney:
  db-server:
    port: 9360
    base-dir: ./.chutney/data/pgdata
    work-dir: ./.chutney/data/pgwork

spring:
  datasource:
    url: jdbc:postgresql://localhost:${chutney.db-server.port}/postgres
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
