spring:
  jpa:
    open-in-view: false
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate.id.new_generator_mappings: false
  datasource:
    url: jdbc:postgresql://localhost:10457/postgres
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
