
chutney:
  security:
    users:
      -
        id: user
        name: user
        firstname: user
        lastname: user
        mail: user@user.com
        password: user
      -
        id: admin
        name: admin
        firstname: admin
        lastname: admin
        mail: admin@admin.com
        password: admin
        roles:
          - ADMIN
