language: java
os: linux
sudo: false # faster builds

cache:
  directories:
  - "$HOME/.m2"
  - "$TRAVIS_BUILD_DIR/ui/node/"
  - "$TRAVIS_BUILD_DIR/ui/node_modules/"

jdk: openjdk8

install: skip

before_script:
  - export BINDIR=$(pwd) && curl -H 'Cache-Control:no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash

script:
  - export MVN_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression="project.version" -q -DforceStdout)
  - echo "MVN_VERSION ${MVN_VERSION} - TRAVIS_TAG ${TRAVIS_BRANCH} - TRAVIS_BRANCH ${TRAVIS_BRANCH}"
  - mvn -B -V install

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ([[ -n "$FOSSA_API_KEY" ]]) && (./fossa analyze)

after_failure:
  - echo "***** PRINT SUREFIRE REPORTS *****" && find . -type f -wholename "*/target/surefire-reports/*.txt" -exec cat {} \;
  - echo "***** PRINT FAILSAFE REPORTS *****" && find . -type f -wholename "*/target/failsafe-reports/*.txt" -exec cat {} \;

deploy:

  - provider: bintray
    skip_cleanup: true
    file: "target/bintray-deploy-descriptor.json"
    user: boddissattva
    key:
      secure: G8rXzZ+z+E0KD4R3hO4EnRQweczB8JCIUB12PiBEa+85qzGGjG07ilzGTZjSutueU4iTu2N39G+MFvYC+vyqV1ufb5/CqkGin9yb3MfGwntN0HMWg4j6ODEQ5Af9vwoqHgJYu0ch3GiklNIA2AVppGM7ECqssouEJxdNzKYVolXTpRqMbaRnFXFi8ir2pVwv71zq9GkpfnOaCef3AsZ3AdOlPXzhmQoh2ORZbsFk3mr81OYiPQgvgAme/gw9uZPDBOn2XrzF8Vk5LAh+cJmN4LixDXflaHZg9MsJdboWpFKksDzw7vHnjcintxbQmolC1p45OQSbxvCsTR1JjeZ/+5fWSEGppIgUy2+ADxR/n+CRuhl6o4Q96LqFKo/aOzlenhxE1TzdV7tdEpsHTfFzXOAO7hr6gtYNAwSB/XoslFWyUHxETxUaZk9MQ6o/tBFcwDylGWEjiUKeY8dHvthnQL+EMJUvgbtE1+LzVTX7IimjpyEHU0pbNJmxugn1ZPaNGtsTpnWEfF5n8f0GeN8s1rgRn3w9vlnr74rNGC8uQf4rn2cb8dGlsksRznZOV1jKQJIWXwrXWGMzs0sX/lVtnw/tZCeYzVcELQQyWcEENz3zddlRGxtMVxZpYiaBarOrK0iomjsp7WaNaZUKGzsxUMIGESQkLE0od5WB2UAV3n0=
    on:
      repo: chutney-testing/chutney
      all_branches: true
      tags: true
      condition: $MVN_VERSION = $TRAVIS_TAG

  - provider: releases
    skip_cleanup: true
    file_glob: true
    file: "packaging/local-dev/target/chutney-*.jar"
    api_key:
      secure: PomXiVGmmaZRg+pjS7hTG9X+WaBaTkVjTwXkua/HNn7eRdweNz2gSMOjBRiuzADS/q/s2zuB4JVhX87BJ2r1/93NZtvs0UwdUTeectfdshJocQYBpS5oDpWUnOeKTkOpZTsTLXXneJ95y8z3Ai+L6urlQTACLlWJ1ZaDnk4+TlDyEW3OZPZKrY6qltHTE+niSlXdEtfri+qExUR5hFM5JOHqYtc3Qzmv/fJrL9Smk9O4a+5piBwdJQN2KoTM0BIduViboOw+YcakkIY9TyCpOCsqhLoGx1IV20h+jfzC/JBm+tpFfAXLWgDQsP/XV3dFkhzEbwWqzABfuVjnUakz81DFzgK9whdTKOIqwIzySUrKhJg/FHaoNYUXmjNCggoeFp4mjLcOuWEhV+bJTWhGMMWxC7Vm7gsSGvmXDILQ51RiPnEDlv/HemS/TzMaAbBz+ic3Y+3Ib0dC0RuWJcs7J94DHY2IuX9FiYdRg2RZ0mcFd3Yx/SISxQGGRkWxqadwc4evKF9Tp7cwdbSVcGlPq4dzp8kMHbvCn7SRhKFNOW7oZg79BIF5vuMw4jdc1WkGCbwfCCrklkAO/VzcE0Kk65+7JW8zW94KiVJtbkL8NyoWMiD+ki54neiBp+5OzpneHv7MNnK3s0ITlCPrRNMeF1/CV2YOuBiBoDq1tUG8vjQ=
    on:
      repo: chutney-testing/chutney
      all_branches: true
      tags: true
      condition: $MVN_VERSION = $TRAVIS_TAG

notifications:
  webhooks:
    - secure: "lVxOUn5+AVbN182QhrKpDZm5BXyRS0rkNE5zHWy9GS1F0ozrXTS1kYuTmMFKWuhwZ3Fj252tMxT772XFdKy72vdOMEA1KCBoKM9bcPfRC9MA8oslhUXjoOv+c+4hQrzyeowyycaXU2AheYV5V+zASxyEOQnH+uZVrxqv2iORCt72d0I7q9XDRRZwCNAIAXBCn4RFbHkcYqXc2sllY1JOuQ0F/1+1V3Xj9FbVVVs6EyQNnLvcw/veExrd7R2xlLz+/V3FQZjAd625gxfwmR9kNEgv9czLqVnawVsh31s14uLOk2R8uy+IjLW6fATgvWrfTOA/FmKo/jBrA/rlA8eHrNRwIfYFv21GOpycsxjVm3XaNSbt4GfxfWK+ZDvZriPdPgoyQJ5+RBWOwD84N+Zkeu/Ldj1paFFXvGXnfhXHwhRZAzCZhXHMkETTr5Cp7Sc/govDREWoC6gfQfoT6EnUlz3PyfdO5Oi0XCs/5xP7v2S4qbzC17ycmaKVUBwqPXzk8e6HqtcbI/c6gFi7oVl7vkC7giyDKc68JWnJx9HdvYpMzxNdMbGlcA8bcGoO0uKR6/Fp6j6DVa36664Tz5+FErqoOU1DjWF0N9IwFEHWlMn70wqWtTvh50eFtLD+XBD0jVM+PQdjwehesPD5AC208dHida9ziGbl0xjC/6bXHU0="
