blank_issues_enabled: false
contact_links:
  - name: Community support
    url: https://github.com/chutney-testing/chutney/discussions
    about: A place to get help, Q&A, new ideas and discussions
  - name: Report vulnerabilities, Live chat and private messages
    url: https://chutney-testing.zulipchat.com/
    about: A more informal place to get in touch if you need it or point to security issues
