name: 🚀 Feature Request
description: Suggest an idea for this project
title: "🚀 | "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        🙌  Please, make sure your feature request is unique 🦄 !
        Did you search issues labeled with Enhancement ? If you find anything relevant to you, up-vote 👍 or add a comment 💬 !
  - type: textarea
    id: use-case
    attributes:
      label: Describe your use case
      placeholder: Describes the context in which the feature will be used. Can you give a concrete example of how you'd use the feature?
    validations:
      required: true
  - type: textarea
    id: related-problems
    attributes:
      label: Is your feature request related to a problem ?
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen. Can you draw a picture of what you're imagining?
    validations:
      required: true
  - type: textarea
    id: examples
    attributes:
      label: Link to examples
      description: Is there other software that has the behavior you're interested in?
      placeholder: What is it, and how does it work? Are there any relevant existing standards or conventions?
    validations:
      required: false
