# emmbedded LDAP
spring:
  ldap:
    embedded:
      base-dn: dc=chutneytesting,dc=com
      credential:
        username: uid=admin
        password: secret
      ldif: classpath:/schema.ldif
      port: 12345
      validation:
        enabled: false

# LDAP authentication
ldap:
  source:
    url: "ldap://localhost:12345"
    base: "dc=chutneytesting,dc=com"
    userDn: "uid=admin"
    password: "secret"
  attributes:
    id: "uid"
    name: "cn"
    firstname: "sn"
    lastname: "sn"
    groups: "isMemberOf"
    mail: "sn"
  groups-pattern: "^cn=chutney(.+),ou=groups,dc=chutneytesting,dc=com$"
  user-search-scope: "SUBTREE"
