name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Deploy to central
    steps:
      - uses: actions/checkout@v2
      - name: Set release version environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up build
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.CHUTNEY_GPG_PRIVATE_KEY }}
          gpg-passphrase: CHUTNEY_GPG_PASSPHRASE

      - name: Build with Maven
        env:
          BUILD_ENV: 'github-actions'
        run: mvn clean -B -V verify

      - name: Publish to central
        run: mvn -DskipTests -Drelease=true deploy
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          CHUTNEY_GPG_PASSPHRASE: ${{ secrets.CHUTNEY_GPG_PASSPHRASE }}

      - name: Create github release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: 'TODO'
          draft: false
          prerelease: false

      - name: Upload fatjar to github release
        id: upload-release-asset-fatjar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/packaging/local-dev/target/chutney-local-dev-${{ env.RELEASE_VERSION }}.jar
          asset_name: chutney-local-dev-${{ env.RELEASE_VERSION }}.jar
          asset_content_type: application/jar

      - name: Upload signature to github release
        id: upload-release-asset-fatjar-sig
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/packaging/local-dev/target/chutney-local-dev-${{ env.RELEASE_VERSION }}.jar.asc
          asset_name: chutney-local-dev-${{ env.RELEASE_VERSION }}.jar.asc
          asset_content_type: application/pgp-signature

